version: "3.7"
services:
    nginx:
        build:
            context: docker/development/nginx
        ports:
            - "8081:80"
        volumes:
            - ./:/app
        depends_on:
            - php-fpm

    node-cli:
        build:
            context: docker/development/node
        volumes:
            - ./:/app

    php-fpm:
        build:
            context: docker/development/php-fpm
        env_file: .env
        environment:
            PHP_IDE_CONFIG: serverName=API
        volumes:
            - ./:/app

    php-cli:
        build:
            context: docker/development/php-cli
        env_file: .env
        volumes:
            - ./:/app

    api-postgres:
        image: postgres:12.2-alpine
        env_file: .env
        environment:
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_DATABASE}
        volumes:
            - api-postgres:/var/lib/postgresql/data
        ports:
            - "54321:5432"

volumes:
    api-postgres:
